[package]
name = "rsreduce"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
structopt.workspace = true
tracing.workspace = true
tree-sitter.workspace = true
tree-sitter-reduce.workspace = true
tree-sitter-rust.workspace = true
walkdir.workspace = true
